export const LightThemeColors ={
    primary: "#1A73E8",
    graySecondary: "#D0DDD0",
    secondary: "#FFFFFF",
    accent: "#E8F0FE",
    textPrimary: "#000000",
    textSecondary: "#5F6368",
    cardBackground: "#F5F5F5",
    buttonBackground: "#1A73E8",
    buttonText: "#FFFFFF",
    borderColor: "#E0E0E0",
    success: "#34A853",
    error: "#EA4335",
    white:'#FFFFFF',
    grayLight:'#EFF3EA',
}